### ISSUE TITLE
`diff` command can't handle arguments

### ISSUE THREAD

**Issue by marstr** [marstr/baronial#61]
Version Information:

Version:  v0.1.2-modified
System: windows/amd64
Go:  go1.13.3
Source Revision:  c6011b059c5af5fb470bd5211a510f029aff8f1d

When you provide any arguments to the `diff` command, the following stack trace pops up:
```
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x82633c]

goroutine 1 [running]:
c000076010, 0xc00008c090, 0x28, ...)
        C:/Users/marstr/go/pkg/mod/github.com/marstr/envelopes@v0.0.0-20190915204657-a43878a91415/persist/refspec.go:164 +0x18c
github.com/marstr/envelopes/persist.RefSpecResolver.Resolve(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9e8420, 0xc000076010, 0xc00008c090, 0x28, ...)
        C:/Users/marstr/go/pkg/mod/github.com/marstr/envelopes@v0.0.0-20190915204657-a43878a91415/persist/refspec.go:59 +0xac
github.com/marstr/baronial/cmd.diffCmd.processArgs(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/code/github.com/marstr/baronial/cmd/diff.go:73 +0x135
github.com/spf13/cobra.(*Command).ValidateArgs(...)
        C:/Users/marstr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:880
github.com/spf13/cobra.(*Command).execute(0xc0002a6000, 0xc000053a80, 0x1, 0x1, 0xc0002a6000, 0xc000053a80)
        C:/Users/marstr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:735 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0xcf22a0, 0x43e3a1, 0xcb45a0, 0xc00004ff50)
        C:/Users/marstr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2f1
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/marstr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/marstr/baronial/cmd.Execute()
        C:/code/github.com/marstr/baronial/cmd/root.go:47 +0x38
main.main()
        C:/code/github.com/marstr/baronial/main.go:21 +0x27
```

I still think that just `baronial diff` is the most important command, but this should get fixed up before v0.1.3

**Comment by marstr** [comment]
Bug still repro on the following system:

```
Version:  v0.2.0-alpha-modified
System: windows/amd64
Go:  go1.12.5
Source Revision:  36f7f1924ae315fe7fbd03b95cd5e08037ed514b
```
